### ISSUE TITLE
[Question] Support for multiline commands?

### ISSUE THREAD

**Issue by riga** [mkdocs-plugins/termynal#10]
Hi! Awesome project!

I was wondering, is there a way to support multiline commands? E.g.:

```
$ some longish command with \
    many \
    many \
    arguments
and this is the output
```

Currently, the "typing" animation only works for the first line of the command and the three additional command lines are interpreted as output and shown instantly after the animation finishes:

```
    many \
    many \
    arguments
and this is the output
```

Thanks!

**Comment by daxartio** [comment]
Hi!

It sounds good. I'll see how to do this

**Comment by daxartio** [comment]
Right now it looks like this

![termynal-miltiline](https://github.com/daxartio/termynal/assets/11211587/9062bfe5-7bb1-4fb9-95c9-826a85a85e0c)

**Comment by riga** [comment]
That's perfect! Thanks for looking into this so quickly.

A new release would be highly appreciated 👍

**Comment by daxartio** [comment]
What do think about it?

![termynal-miltiline2](https://github.com/daxartio/termynal/assets/11211587/77b9e2b1-ccc7-44c0-8d81-826f99bb269e)

**Comment by riga** [comment]
Personally, I would prefer the first solution with just one $ in the first line since it's easier to copy the command.

**Comment by daxartio** [comment]
Just a moment

**Comment by daxartio** [comment]
Actually, you copy the command without `$`

<img width="852" alt="Снимок экрана 2023-07-22 в 18 37 17" src="https://github.com/daxartio/termynal/assets/11211587/bbc234c7-3e5d-428d-a841-d19c47b038f1">

Else it looks like this

![termynal-miltiline3](https://github.com/daxartio/termynal/assets/11211587/94d05eab-0307-42e6-9137-d09bd705a7fb)

Let's poll for the best variant.

1st - 👍🏻  
2sn - 😄

**Comment by riga** [comment]
Before voting ^^ just one question. Would it be possible to preserve the indentation of the other command lines?

**Comment by daxartio** [comment]
I wanted to to that, but i'll need to think about it more time

**Comment by riga** [comment]
If that works, then I'm for option two :)

**Comment by daxartio** [comment]
Ok, i'll do this as a default and a user can choose option by plugin's configuration

**Comment by daxartio** [comment]
![tm4](https://github.com/daxartio/termynal/assets/11211587/14386f44-71e7-45e1-a544-63900633b1f9)

**Comment by daxartio** [comment]
Added in v0.5.0

**Comment by riga** [comment]
Awesome 👏
