### ISSUE TITLE
Progress bar is not responsive (or not respecting the limits)

### ISSUE THREAD

**Issue by Guts** [mkdocs-plugins/termynal#15]
To reproduce:

1. Open https://daxartio.github.io/termynal/ on a smartphone's browser (FF on Android for example or Firefox on Desktop and Ctrl + M)
2. The progress bar extends beyond the frame on the right:

![image](https://github.com/daxartio/termynal/assets/1596222/4ef5db6a-8702-42cc-934c-06db0a8dbbf8)

**Comment by daxartio** [comment]
Thank you @Guts 

I fixed it in 0.10.1

I decided to fix it fast way. If you have remarks i will be glade to hear them

**Comment by Guts** [comment]
Fixed. Thanks you!

I close here.
